apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-simulation-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-simulation-server
  template:
    metadata:
      labels:
        app: network-simulation-server
    spec:
      containers:
      - name: app
        image: gcr.io/properties-observability/main-app:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: network-config
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: network-secrets
              key: mongodb-uri
        - name: MONGODB_DB
          value: network_sim_db
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: network-secrets
              key: rabbitmq-url
        ports:
        - containerPort: 9090
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: network-simulation-server
spec:
  type: LoadBalancer
  selector:
    app: network-simulation-server
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: alt-http
      protocol: TCP
      port: 8080
      targetPort: 8080 