apiVersion: batch/v1
kind: Job
metadata:
  name: consumer-simulations-worker
spec:
  template:
    spec:
      containers:
      - name: consumer-simulations-worker
        image: gcr.io/[YOUR-PROJECT-ID]/consumer-simulations-worker:latest
        command: ["python", "-m", "app.workers.consumer_workers.consumer_simulations_worker"]
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        - name: RABBITMQ_URI
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: uri
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: OnFailure 