FROM python:3.10-slim
WORKDIR /app
COPY app /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
ENV PYTHONPATH=/app
CMD ["python", "app/workers/publish_workers/publish_simulations_worker.py"] 