FROM python:3.10-slim
WORKDIR /app
COPY ../app /app
COPY ../requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
ENV PYTHONPATH=/app
CMD ["python", "app/workers/outbox_publishers_workers/publish_completed_worker.py"] 