services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: network-simulation-server
    env_file:
      - ../.env
    environment:
      # Override or add environment variables here if needed
      MONGODB_URI: "mongodb+srv://eliitzh17:AX3lGegN341ozKF2@cluster0.qp71kbn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "network_sim_db"
      RABBITMQ_URL: "amqps://zzwmeqgv:CBqAUi7xOh0u8hj8mt9IDmpcQrJofi1H@horse.lmq.cloudamqp.com/zzwmeqgv"
      # Add other environment variables as needed
    ports:
      - "9090:9090"
    restart: unless-stopped
    command: [ "python", "main.py" ]

  handle_simulation_worker:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ../.env
    environment:
      PYTHONPATH: /app
      MONGODB_URI: "mongodb+srv://eliitzh17:AX3lGegN341ozKF2@cluster0.qp71kbn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "network_sim_db"
      RABBITMQ_URL: "amqps://zzwmeqgv:CBqAUi7xOh0u8hj8mt9IDmpcQrJofi1H@horse.lmq.cloudamqp.com/zzwmeqgv"
    restart: unless-stopped
    command: [ "python", "app/workers/handle_simulation_worker.py" ]

  handle_links_worker:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ../.env
    environment:
      PYTHONPATH: /app
      MONGODB_URI: "mongodb+srv://eliitzh17:AX3lGegN341ozKF2@cluster0.qp71kbn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "network_sim_db"
      RABBITMQ_URL: "amqps://zzwmeqgv:CBqAUi7xOh0u8hj8mt9IDmpcQrJofi1H@horse.lmq.cloudamqp.com/zzwmeqgv"
    restart: unless-stopped
    command: [ "python", "app/workers/handle_links_worker.py" ]

  handle_in_post_link_worker:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ../.env
    environment:
      PYTHONPATH: /app
      MONGODB_URI: "mongodb+srv://eliitzh17:AX3lGegN341ozKF2@cluster0.qp71kbn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "network_sim_db"
      RABBITMQ_URL: "amqps://zzwmeqgv:CBqAUi7xOh0u8hj8mt9IDmpcQrJofi1H@horse.lmq.cloudamqp.com/zzwmeqgv"
    restart: unless-stopped
    command: [ "python", "app/workers/handle_in_post_link_worker.py" ]
