services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: network-simulation-server
    env_file:
      - ../.env
    environment:
      # Override or add environment variables here if needed
      MONGODB_URI: "mongodb+srv://eliitzh17:AX3lGegN341ozKF2@cluster0.qp71kbn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "network_sim_db"
      RABBITMQ_URL: "amqps://zzwmeqgv:CBqAUi7xOh0u8hj8mt9IDmpcQrJofi1H@horse.lmq.cloudamqp.com/zzwmeqgv"
      # Add other environment variables as needed
    ports:
      - "9090:9090"
    restart: unless-stopped
    command: [ "python", "main.py" ]

  worker_consumer_simulations:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: /app
      MONGODB_URI: "mongodb+srv://eliitzh17:AX3lGegN341ozKF2@cluster0.qp71kbn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "network_sim_db"
      RABBITMQ_URL: "amqps://zzwmeqgv:CBqAUi7xOh0u8hj8mt9IDmpcQrJofi1H@horse.lmq.cloudamqp.com/zzwmeqgv"
    restart: unless-stopped
    command: [ "python", "app/workers/consumer_workers/consumer_simulations_worker.py" ]

  worker_consumer_links:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: /app
      MONGODB_URI: "mongodb+srv://eliitzh17:AX3lGegN341ozKF2@cluster0.qp71kbn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "network_sim_db"
      RABBITMQ_URL: "amqps://zzwmeqgv:CBqAUi7xOh0u8hj8mt9IDmpcQrJofi1H@horse.lmq.cloudamqp.com/zzwmeqgv"
    restart: unless-stopped
    command: [ "python", "app/workers/consumer_workers/consumer_links_worker.py" ]

  worker_publish_simulations:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: /app
      MONGODB_URI: "mongodb+srv://eliitzh17:AX3lGegN341ozKF2@cluster0.qp71kbn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "network_sim_db"
      RABBITMQ_URL: "amqps://zzwmeqgv:CBqAUi7xOh0u8hj8mt9IDmpcQrJofi1H@horse.lmq.cloudamqp.com/zzwmeqgv"
    restart: unless-stopped
    command: [ "python", "app/workers/outbox_producers_workers/publish_simulations_worker.py" ]

  worker_publish_links:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: /app
      MONGODB_URI: "mongodb+srv://eliitzh17:AX3lGegN341ozKF2@cluster0.qp71kbn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "network_sim_db"
      RABBITMQ_URL: "amqps://zzwmeqgv:CBqAUi7xOh0u8hj8mt9IDmpcQrJofi1H@horse.lmq.cloudamqp.com/zzwmeqgv"
    restart: unless-stopped
    command: [ "python", "app/workers/outbox_producers_workers/publish_links_worker.py" ]

  worker_publish_completed:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: /app
      MONGODB_URI: "mongodb+srv://eliitzh17:AX3lGegN341ozKF2@cluster0.qp71kbn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "network_sim_db"
      RABBITMQ_URL: "amqps://zzwmeqgv:CBqAUi7xOh0u8hj8mt9IDmpcQrJofi1H@horse.lmq.cloudamqp.com/zzwmeqgv"
    restart: unless-stopped
    command: [ "python", "app/workers/outbox_producers_workers/publish_completed_worker.py" ]
