apiVersion: batch/v1
kind: Job
metadata:
  name: publish-completed-worker
spec:
  template:
    spec:
      containers:
      - name: publish-completed-worker
        image: gcr.io/[YOUR-PROJECT-ID]/publish-completed-worker:latest
        command: ["python", "-m", "app.workers.outbox_publishers_workers.publish_completed_worker"]
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        - name: RABBITMQ_URI
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: uri
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: OnFailure 